from fastapi import FastAPI
from pydantic import BaseModel, EmailStr
from typing import Any

app = FastAPI()


class ItemBase(BaseModel):
    name: str
    description: str | None = None
    price: float
    tax: float | None = None


class ItemCreate(ItemBase):
    pass


class ItemResponse(ItemBase):
    id: int
    price_with_tax: float | None = None


class UserBase(BaseModel):
    username: str
    email: EmailStr
    full_name: str | None = None


class UserIn(UserBase):
    password: str


class UserOut(UserBase):
    pass


@app.get("/")
async def root():
    return {"message": "Hello World"}


@app.post("/items/", response_model=ItemResponse)
async def create_item(item: ItemCreate) -> Any:
    """
    Create a new item with automatic tax calculation.
    """
    item_dict = item.model_dump()
    item_dict["id"] = 1  # In a real app, this would be generated by the database
    
    if item.tax is not None:
        price_with_tax = item.price + item.tax
        item_dict["price_with_tax"] = price_with_tax
    
    return item_dict


@app.get("/items/{item_id}", response_model=ItemResponse)
async def read_item(item_id: int):
    """
    Retrieve an item by ID.
    """
    # Mock data - in a real app, this would query a database
    item_data = {
        "id": item_id,
        "name": "Sample Item",
        "description": "A sample item description",
        "price": 99.99,
        "tax": 8.99,
        "price_with_tax": 108.98
    }
    return item_data


@app.post("/user/", response_model=UserOut)
async def create_user(user: UserIn) -> Any:
    """
    Create a new user. Password is not returned in the response for security.
    """
    user_dict = user.model_dump()
    user_dict["id"] = 1  # In a real app, this would be generated by the database
    return user_dict


# Return Type Annotation Examples
class ItemWithTags(BaseModel):
    name: str
    description: str | None = None
    price: float
    tax: float | None = None
    tags: list[str] = []


@app.post("/items/with-tags/", response_model=ItemWithTags)
async def create_item_with_tags(item: ItemWithTags) -> ItemWithTags:
    """
    Create an item using return type annotation for validation and documentation.
    """
    return item


@app.get("/items/list/", response_model=list[ItemWithTags])
async def list_items() -> list[ItemWithTags]:
    """
    Return a list of items using return type annotation.
    """
    return [
        ItemWithTags(name="Portal Gun", price=42.0, tags=["sci-fi", "weapon"]),
        ItemWithTags(name="Plumbus", price=32.0, tags=["household", "tool"]),
    ]


# response_model_exclude_unset Example
class ItemWithDefaults(BaseModel):
    name: str
    description: str | None = None
    price: float
    tax: float = 10.5
    tags: list[str] = []


items_db = {
    "foo": {"name": "Foo", "price": 50.2},
    "bar": {"name": "Bar", "description": "The bartenders", "price": 62, "tax": 20.2},
    "baz": {"name": "Baz", "description": None, "price": 50.2, "tax": 10.5, "tags": []},
}


@app.get("/items/{item_id}/minimal", response_model=ItemWithDefaults, response_model_exclude_unset=True)
async def read_item_minimal(item_id: str):
    """
    Return item excluding unset default values.
    Only fields explicitly set will be included in the response.
    """
    return items_db[item_id]


# response_model_include and response_model_exclude Examples
@app.get(
    "/items/{item_id}/name-only",
    response_model=ItemWithDefaults,
    response_model_include={"name", "description"},
)
async def read_item_name_only(item_id: str):
    """
    Return item with only name and description fields included.
    """
    return items_db[item_id]


@app.get(
    "/items/{item_id}/public",
    response_model=ItemWithDefaults,
    response_model_exclude={"tax"},
)
async def read_item_public(item_id: str):
    """
    Return item excluding the tax field.
    """
    return items_db[item_id]
