from fastapi import FastAPI
from pydantic import BaseModel, EmailStr
from typing import Any

app = FastAPI()


class ItemBase(BaseModel):
    name: str
    description: str | None = None
    price: float
    tax: float | None = None


class ItemCreate(ItemBase):
    pass


class ItemResponse(ItemBase):
    id: int
    price_with_tax: float | None = None


class UserBase(BaseModel):
    username: str
    email: EmailStr
    full_name: str | None = None


class UserIn(UserBase):
    password: str


class UserOut(UserBase):
    pass


@app.get("/")
async def root():
    return {"message": "Hello World"}


@app.post("/items/", response_model=ItemResponse)
async def create_item(item: ItemCreate) -> Any:
    """
    Create a new item with automatic tax calculation.
    """
    item_dict = item.model_dump()
    item_dict["id"] = 1  # In a real app, this would be generated by the database
    
    if item.tax is not None:
        price_with_tax = item.price + item.tax
        item_dict["price_with_tax"] = price_with_tax
    
    return item_dict


@app.get("/items/{item_id}", response_model=ItemResponse)
async def read_item(item_id: int):
    """
    Retrieve an item by ID.
    """
    # Mock data - in a real app, this would query a database
    item_data = {
        "id": item_id,
        "name": "Sample Item",
        "description": "A sample item description",
        "price": 99.99,
        "tax": 8.99,
        "price_with_tax": 108.98
    }
    return item_data


@app.post("/user/", response_model=UserOut)
async def create_user(user: UserIn) -> Any:
    """
    Create a new user. Password is not returned in the response for security.
    """
    user_dict = user.model_dump()
    user_dict["id"] = 1  # In a real app, this would be generated by the database
    return user_dict
