from datetime import datetime, timezone
from typing import Any, Generic, TypeVar
from enum import Enum

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, EmailStr, Field

app = FastAPI()

# API Version
API_VERSION = "v1"

# Generic Type for Response Data
T = TypeVar("T")

# Response Envelope Models
class Meta(BaseModel):
    """Metadata for API responses"""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    version: str = API_VERSION


class SuccessResponse(BaseModel, Generic[T]):
    """Standard success response envelope"""
    data: T
    meta: Meta = Field(default_factory=Meta)


# Error Envelope Models
class ErrorCode(str, Enum):
    """Standardized error codes"""
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"


class ErrorDetail(BaseModel):
    """Detailed error information"""
    field: str | None = None
    message: str


class ErrorResponse(BaseModel):
    """Standard error response envelope"""
    error: dict
    meta: Meta = Field(default_factory=Meta)

    @classmethod
    def create(cls, code: ErrorCode, message: str, details: list[ErrorDetail] | None = None):
        """Factory method to create error response"""
        error_dict = {
            "code": code.value,
            "message": message
        }
        if details:
            error_dict["details"] = [d.model_dump() for d in details]
        return cls(error=error_dict)


# Pagination and Filter Models
class SortOrder(str, Enum):
    """Sort order options"""
    asc = "asc"
    desc = "desc"


class PaginationParams(BaseModel):
    """Global pagination parameters"""
    offset: int = Field(default=0, ge=0, description="Number of items to skip")
    limit: int = Field(default=100, ge=1, le=100, description="Maximum number of items to return")


class SortParams(BaseModel):
    """Global sort parameters"""
    sort_by: str = Field(default="id", description="Field to sort by")
    order: SortOrder = Field(default=SortOrder.asc, description="Sort order")


class FilterOperator(str, Enum):
    """Filter operators"""
    equals = "equals"
    contains = "contains"
    starts_with = "starts_with"
    ends_with = "ends_with"
    greater_than = "greater_than"
    less_than = "less_than"


class FilterParam(BaseModel):
    """Single filter parameter"""
    field: str
    operator: FilterOperator = FilterOperator.equals
    value: str


# Domain Models
class ItemBase(BaseModel):
    name: str
    description: str | None = None
    price: float
    tax: float | None = None


class ItemCreate(ItemBase):
    pass


class ItemResponse(ItemBase):
    id: int
    price_with_tax: float | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class UserBase(BaseModel):
    username: str
    email: EmailStr
    full_name: str | None = None


class UserIn(UserBase):
    password: str


class UserOut(UserBase):
    id: int
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# API v1 Endpoints
@app.get("/api/v1/health")
async def health_check():
    """Health check endpoint"""
    return SuccessResponse(
        data={"status": "healthy", "service": "8stages-api"}
    )


@app.post("/api/v1/items/")
async def create_item(item: ItemCreate) -> SuccessResponse:
    """
    Create a new item with automatic tax calculation.
    """
    item_dict = item.model_dump()
    item_dict["id"] = 1  # In a real app, this would be generated by the database
    
    if item.tax is not None:
        price_with_tax = item.price + item.tax
        item_dict["price_with_tax"] = price_with_tax
    
    return SuccessResponse(data=ItemResponse(**item_dict))


@app.get("/api/v1/items/{item_id}")
async def read_item(item_id: int) -> SuccessResponse:
    """
    Retrieve an item by ID.
    """
    # Mock data - in a real app, this would query a database
    item_data = {
        "id": item_id,
        "name": "Sample Item",
        "description": "A sample item description",
        "price": 99.99,
        "tax": 8.99,
        "price_with_tax": 108.98,
        "created_at": datetime.now(timezone.utc)
    }
    return SuccessResponse(data=ItemResponse(**item_data))


@app.get("/api/v1/items/")
async def list_items(
    offset: int = 0,
    limit: int = 100,
    sort_by: str = "id",
    order: SortOrder = SortOrder.asc
) -> SuccessResponse:
    """
    List items with pagination and sorting.
    Global list conventions applied.
    """
    # Mock data - in a real app, this would query a database
    items = [
        ItemResponse(
            id=1,
            name="Portal Gun",
            description="Interdimensional travel device",
            price=42.0,
            tax=3.5,
            price_with_tax=45.5,
            created_at=datetime.now(timezone.utc)
        ),
        ItemResponse(
            id=2,
            name="Plumbus",
            description="Household tool",
            price=32.0,
            tax=2.7,
            price_with_tax=34.7,
            created_at=datetime.now(timezone.utc)
        ),
    ]
    
    # Apply pagination
    paginated_items = items[offset:offset + limit]
    
    return SuccessResponse(data=paginated_items)


@app.post("/api/v1/users/")
async def create_user(user: UserIn) -> SuccessResponse:
    """
    Create a new user. Password is not returned in the response for security.
    """
    user_dict = user.model_dump()
    user_dict["id"] = 1  # In a real app, this would be generated by the database
    user_dict.pop("password")  # Remove password from response
    
    return SuccessResponse(data=UserOut(**user_dict))


@app.get("/api/v1/users/{user_id}")
async def read_user(user_id: int) -> SuccessResponse:
    """
    Retrieve a user by ID.
    """
    # Mock data - in a real app, this would query a database
    user_data = {
        "id": user_id,
        "username": "johndoe",
        "email": "john@example.com",
        "full_name": "John Doe",
        "created_at": datetime.now(timezone.utc)
    }
    return SuccessResponse(data=UserOut(**user_data))
